server:
  port: 8080

spring:
  application:
    name: task-manager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/task_manager
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  liquibase:
    change-log: classpath:db/master.xml

app:
  jwtSecret: "5f8c0f7a248a548d83e00c6438d9b3fa303e7a07b781898631686d74d1626e29"
  jwtExpirationInMs: 10000000