server:
  port: 8080

spring:
  application:
    name: task-manager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/task_manager
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

app:
  jwtSecret: "4D635166546A576E5A7234753778214125442A472D4B6150645267556B587032"
  jwtExpirationInMs: 10000000